- busted.lua
- busted/init.lua
- busted/runner.lua
- spec/executors_spec.lua
This address issue #320, allowing helper modules to declare tests like:
```lua
-- test_helper.lua
local it = require 'busted'.it
local function make_test(a, b)
it('should check ' .. a .. ' same as ' .. b, function()
assert.same(a, b)
end)
end
return {
make_test = make_test
}
```
And then use the helper modules like:
```lua
-- test_spec.lua
local make_test = require 'test_helpers'.make_test
describe('things', function()
make_test(1, 2)
make_test(4, 4)
end)
```
This is done by exposing the busted executor functions via `require 'busted'` ~~or `require 'busted.executors'`~~ so they can be imported by helper modules.
> Access spec declaration methods

- busted/outputHandlers/base.lua
This change updates the order that error, failure, and pending messages are displayed such that they are reported in the same order as when they occurred. Messages are still grouped according to their type, where all pending messages are grouped together, all failure messages are grouped together, etc. This allows for the same exact output messages to be generated in the same exact order each time a test suite is executed
with the same command-line options.
> Display error and failure messages in the order they occur

- .travis_setup.sh
Switch to using `wget` instead of `curl` in travis setup so that site redirection will work when downloading source packages.
This allows the travis build to work when luarocks.org is down, but being redirected to another site (like it currently is).
> Use wget in travis setup instead of curl

- .travis_setup.sh
- busted/modules/configuration_loader.lua
- busted/runner.lua
- spec/cl_lua_path.lua
- spec/cl_spec.lua
- spec/cl_test_module.lua
This fixes issue #327
- The default `.busted` task was overriding the command-line argument for `--lpath`
> Fix issue #327 busted --lpath isn't functioning 

- .travis_setup.sh
- busted/modules/output_handler_loader.lua
- spec/cl_spec.lua
This allows an output handler to be loaded from a module found in the Lua search path (or path specified by the --lpath option). The output handler can still be loaded from a lua or moonscript file as well. If the output handler specified on the command line cannot be found in `busted/outputHandlers/`, then attempt to load
the output handler as if it were in the Lua module search path.
> Support loading output handler via Lua search path

- busted-2.0.rc6-0.rockspec
- busted/runner.lua
Set default output handler to `utfTerminal` if `stdout` is a tty, otherwise set the default output handler to `plainTerminal`.
This allows file redirection to automatically default to `plainTerminal`.  For example
```
$ busted > log.txt
```
will use `plainTerminal`, while
```
$ busted
```
will use `utfTerminal`.
In addition, there is no need to have any special logic for Windows since the `ansicolors` module already takes care of this by removing any ansi color codes when running on Windows, only enabling ansi color codes when ansicon is present.
> Default output handler depends on stdout is a tty

- busted/init.lua
- spec/executors_spec.lua
This allows helper modules to use variables/functions declared in the busted environment, such as `assert`, `spy`, `mock`, `stub`, etc. This complements the spec declarations methods (`describe`, `it`, etc.), which can already be used by helper modules.
> Access for busted root context environment variables

- busted/runner.lua
Calls `os.exit` with `close=true` to allow Lua to close the Lua state before exiting.
> Close Lua state on exit

- busted/outputHandlers/utfTerminal.lua
Use different characters for success, failure, error, and pending status dots:
* Success - filled circle
* Failure - filled square
* Error   - heavy asterisk
* Pending - dotted circle
```
●●◼◼✱✱◌◌
2 successes / 2 failures / 2 errors / 2 pending : 0.0 seconds
```
> Update status 'dot' characters for utf terminal

- busted/init.lua
- busted/outputHandlers/base.lua
This fixes the case where errors are double counted when there is an error in a support function (`setup`, `teardown`, `before_each`, `after_each`)
> Fix double counting of errors

- busted/outputHandlers/TAP.lua
Enable stack trace info in TAP failures with the verbose option.
```
$ busted -v -o TAP
1..6
ok 1 - Tests success1
ok 2 - Tests success2
not ok 3 - Tests error1
#
not ok 4 - Tests error2
#
not ok 5 - Tests failure1
#
not ok 6 - Tests failure2
#
```
> Add stack trace to TAP failure message

- busted/init.lua
- busted/outputHandlers/sound.lua
- busted/utils.lua
Fixed cases where variables were being used before they were initialized (mentioned in PR #348).
> Fix variables used before they are initialized

- .travis.yml
- busted-scm-0.rockspec
Right now it's difficult to install busted from source from the master branch. Currenlty I have to check out the repo then do a `luarocks make` on the rockspec that is in there. This rockspec installs from the git repository. 
I typically keep the SCM up to date in the repo root, and use it as a template when creating versioned releases. (and I don't check in the versioned rockspecs) I also suggest uploading the SCM rockspec to moonrocks, it will automatically get put in the SCM only manifest so other people can find it.
> Add SCM rockspec

- busted/outputHandlers/junit.lua
Insert timestamp in each test suite header instead of the overall header for all test suites.
> Insert junit timestamp in each test suite

- busted-2.0.rc6-0.rockspec
- busted-scm-0.rockspec
- busted/modules/configuration_loader.lua
- busted/runner.lua
- spec/modules/configuration_loader_spec.lua
This updates the configuration loader to merge command-line options with a specified configuration task, taking in order of precedence:
1. Options specified on the command-line
2. Options specified in the configuration file
3. Built-in command-line option defaults
Also, exit with error when there is an error loading the configuration.
Fix issue #356
> Fix configuration loading

- busted/languages/en.lua
- busted/languages/fr.lua
- busted/modules/test_file_loader.lua
- busted/runner.lua
- spec/cl_spec.lua
Update error messages with "Error:" prefix and validate numeric command line options.
> Update error messages

- busted/runner.lua
Runner currently passes array with an empty string to helpers if no arguments are provided using -X\<helper\> options. This causes error when helper calls cli_args:parse on args. The issue is that when `cliArgs.Xoutput` is nil, `utils.split(cliArgs.Xoutput or '', ',') or {}` == `utils.split('', ',') or {}` == `{''} or {}` == `{''}`.
> Fix passing arguments to helpers

- busted-scm-0.rockspec
- busted/outputHandlers/utfTerminal.lua
Since lua-term is already used and has a submodule equivalent to ansicolors,
use lua-term for color handling. Removed ansicolors dependency from rockspec.
> Replace ansicolors with lua-term

- busted/outputHandlers/utfTerminal.lua
This fixes an issue with #373: unlike ansicolors, lua-term does not disable colors on Windows where it is typically not supported.
> Do not use colors on Windows if ANSICON is not defined

- busted/modules/helper_loader.lua
This should fix #379 when a helper script is used.
> Restore arg after loading helper script

- busted/core.lua
- busted/init.lua
- busted/modules/filter_loader.lua
- busted/modules/helper_loader.lua
- busted/modules/output_handler_loader.lua
- busted/outputHandlers/TAP.lua
- busted/outputHandlers/base.lua
- busted/outputHandlers/json.lua
- busted/outputHandlers/junit.lua
- busted/outputHandlers/plainTerminal.lua
- busted/outputHandlers/sound.lua
- busted/outputHandlers/utfTerminal.lua
- busted/runner.lua
- spec/cl_output_handler.lua
- spec/export_spec.lua
This exports additional functions/variables so they can be accessible to helper modules and output handlers.  With this change, output handlers no longer need to be passed the `busted` object.  Instead, they can just do `require 'busted'` and use the externally available API.
```lua
-- output handler
return function(options)
local busted = require 'busted'
local handler = require 'busted.outputhandlers.base'()
...
busted.subscribe({'test', 'start'}, handler.testStart, { predicate = handler.cancelOnPending })
busted.subscribe({'test', 'end'}, handler.testEnd, { predicate = handler.cancelOnPending })
...
end
```
> Export additional functions to external API

- busted/block.lua
- spec/core_spec.lua
- spec/randomize_spec.lua
This adds a `norandomize` function to file and describe contexts so that test randomization within the current context block can be explicitly disabled, overriding any command-line flags to enable randomization.
```lua
describe('Non-randomized tests', function()
-- Disable randomization for current block when command-line flag forces randomization
norandomize()
...
end)
```
As with the `randomize` function, `norandomize` does not apply to nested blocks.
> Support disabling randomization in context blocks

- busted-2.0.rc7-0.rockspec
- busted-scm-0.rockspec
- busted/execute.lua
- busted/init.lua
- busted/outputHandlers/gtest.lua
- busted/runner.lua
This outputs the test name before a test is run and outputs any failures/errors as they are encountered. The `--defer-print` option can be used to defer the output of failures/errors to the end of the test suite.
Basically adds an output handler that mirrors the gtest unit test output format (which seems to provide everything that #375 is asking for), adding error and skipped test detection.  Like gtest, this output handler will also display color when a tty is detected.
```
$ busted -o gtest 
[==========] Running tests from scanned files.
[----------] Global test environment setup.
[----------] Running tests from spec/test_spec.lua
[ RUN      ] spec/test_spec.lua @ 6: Tests success1
[       OK ] spec/test_spec.lua @ 6: Tests success1 (0.02 ms)
[ RUN      ] spec/test_spec.lua @ 9: Tests …
```
> Add a gtest style output handler

- busted-2.0.rc7-0.rockspec
- busted-scm-0.rockspec
- busted/modules/cli.lua
- busted/modules/helper_loader.lua
- busted/modules/output_handler_loader.lua
- busted/runner.lua
- busted/utils.lua
- spec/cl_spec.lua
This updates the version of penlight used by busted to the version of penlight that fixes `path.normpath`. With the updated version of penlight, busted no longer needs its own version of `normpath`, it can just use `path.normpath` directly from the penlight module.
> Upgrade penlight version

- busted-2.0.rc7-0.rockspec
- busted-scm-0.rockspec
The junit and gtest handlers both require luasocket in order to ```socket.gettime()```
> Add missing luasocket dependency

- busted/block.lua
- spec/core_spec.lua
- spec/randomize_spec.lua
This removes the `norandomize` function  and overloads the `randomize` function to take an argument to enable/disable randomization. Calling `randomize` with no arguments enables randomization by default.
```lua
describe('Do not randomize in this block', function()
randomize(false) -- or randomize(nil)
...
end)
```
```lua
describe('Force randomization in this block', function()
randomize() -- or randomize(true)
...
end)
```
> Replace norandomize() with randomize(false)

- spec/cl_spec.lua
This updates the moonscript specs to detect whether or not moonscript is installed on the system, and if not marks all moonscript tests as pending, instead of attempting to execute them.
> Only run moonscript tests if moonscript is installed

- busted-scm-0.rockspec
This undos the previous change to use https protocol for git since luarocks does not support https using git.
> Use git protocol in scm rockspec

- busted/context.lua
- busted/core.lua
- busted/runner.lua
Use `debug.getmetatable` instead of `getmetatable` in case there is a `__metatable` field present in the object's metatable.
>**getmetatable (object)**
>
If object does not have a metatable, returns nil. Otherwise, if the object's metatable has a "__metatable" field, returns the associated value. Otherwise, returns the metatable of the given object.
> Fix getmetatable calls

- busted/outputHandlers/gtest.lua
Removes unused argument to the gtest output handler.
> Remove unnecessary arg to gtest output handler

- index.html
Example cannot next an `it` block inside another `it` block
> Fix website finally example

- index.html
This makes the following documentation changes to the website:
* Update the supported language list
* Update randomize section
* Add a section for Matchers
* Add a section for `insulate` and `expose` blocks
* Add lazy/strict `setup`/`teardown` description
> Update website documentation

- .travis.yml
- .travis_setup.sh
- busted/context.lua
- busted/core.lua
- busted/execute.lua
- busted/init.lua
- busted/outputHandlers/gtest.lua
- busted/outputHandlers/junit.lua
- busted/outputHandlers/plainTerminal.lua
- busted/outputHandlers/utfTerminal.lua
This wraps publishing of `start` and `end` messages in a `safe` call.  By wrapping `publish` in `safe` if an error is thrown in a `start` message handler, the `end` message will still be published and the current block will be skipped.  This makes `start` and `end` messages work similar to `setup` and `teardown` functions.
> Wrap publish start/end messages in a safe call

- busted/compatibility.lua
Do not perform manual garbage collection if running a LuaJIT version that supports the `close` argument to `os.exit`.
> Update osexit for LuaJIT

- bin/busted
- busted-2.0.rc10-0.rockspec
- busted-scm-0.rockspec
- busted/compatibility.lua
- busted/modules/cli.lua
- busted/options.lua
- busted/outputHandlers/base.lua
- busted/outputHandlers/plainTerminal.lua
- busted/outputHandlers/utfTerminal.lua
- busted/runner.lua
- spec/modules/cli_spec.lua
A few refactors
* Default options
* Calls to `os.exit()`
* Use `socket.gettime()` instead of `os.clock()`
> Minor refactors

- busted/core.lua
- spec/cl_gc_error.lua
- spec/cl_spec.lua
This handles errors from __gc metamethods as well as any other errors that are not caught by xpcall.
> Handle errors from __gc metamethods

- busted/outputHandlers/base.lua
Looks like the json module has issues with tables that have functions in them. So remove output tables that have functions.
Fixes issue #448.
> Fix json output

- busted/modules/configuration_loader.lua
- busted/modules/output_handler_loader.lua
- busted/runner.lua
This just cleans up the calls to the various loaders (i.e. output handler, filter loader, helper loader).
> Refactor calls to module loaders

- busted/compatibility.lua
This fixes the stack trace on exiting with an error code on Lua 5.3.  On Lua 5.3, `error()` is not silent, so don't throw an `error()` to exit with error for Lua > 5.2. For Lua versions 5.1 and 5.2 continue to throw a silent `error()` to allow the Lua state to be closed naturally whenever possible.
> Fix unintentional stack trace on exit

- busted-2.0.rc10-1.rockspec
- busted-scm-0.rockspec
lua_cliargs 3.0.rc-1 was released a few hours ago and unfortunately Luarocks determined that this was < 3.0. So, if you install the current busted 2.0 RC it will install this incompatible version of lua_cliargs.
This change ensures that no 3.0 RCs are installed for lua_cliargs.
> Ensure that pre-release versions of lua_cliargs 3 aren't used as a dependency

- busted/compatibility.lua
- busted/modules/cli.lua
- spec/cl_spec.lua
- spec/lua.lua
@ajacksified @leafo @calio @o-lim 
This is a giant hack, but it works! The correct fix is not in busted, but in luarocks. Currently, luarocks wraps binaries in a shell script that forces a particular interpreter on us, the one that luarocks is configured for.
> Implement option to choose the lua interpreter

- busted-2.0.rc11-0.rockspec
- busted/modules/cli.lua
- spec/cl_helper_script.lua
- spec/cl_output_handler.lua
This patch applies the necessary changes to use the 3.0 version of
lua_cliargs. Please note that this PR can not be merged just yet as we have to release
the cliargs package first.
I've tried to make busted make use of the new `cli:load_defaults` hook for applying defaults from the files (what the `configLoader` module generates), but unfortunately I'm  not familiar enough with the specs to be able to tell what's going on easily.
> Upgrade to lua_cliargs 3.0.rc-1

- busted-scm-0.rockspec
This fixes the scm rockspec to use correct version of lua_cliargs.
> Fix scm-rockspec with correct lua_cliargs version

- busted-scm-0.rockspec
- busted/init.lua
- spec/core_spec.lua
- spec/export_spec.lua
This adds the `match` function from `luassert` to the busted test environment and exports it as part of the busted public API.
> Add `match` to busted env and exported functions

- busted-scm-0.rockspec
- busted/outputHandlers/base.lua
This allows for adding new keys to a test context without the need to change the output handlers in order to copy a new or changed key. We can't just copy the entire table, otherwise the json output handler will break. The `env` key and any values that evaluate to functions cannot be copied.
> Refactor copying of context in base output handler

- busted/outputHandlers/junit.lua
I'm testing version 2.0.rc11-0 and having an issue with the junit output handler crashing lua.
After a little digging, I found it's related to the call to os.date to format the junit timestamp.  The date format string is `'!%Y-%m-%dT%T'`, however the %T format specifier doesn't seem to be available on my platform. Changing the %T to %H:%M:%S in accordance to the strftime documentation resolves the issue.
> Fix to junit timestamp string format:

- busted/outputHandlers/junit.lua
When trying to hook busted's junit output module up to an internal
automated test system it is very challenging to determine what output
was written to stdout by tests, and what output was written to stdout by
tests and what output is part of the test summary in xml. The simplest
way to handle this is to allow junit to accept an argument naming a file
where the xml output should be written via the -Xoutput mechanism. This
patch adds this change to junit.
> Allow junit output handler to save output to file

- busted/core.lua
- busted/outputHandlers/base.lua
- busted/outputHandlers/gtest.lua
- busted/outputHandlers/junit.lua
Move the computation and recording of test execution time to the core and insert the start/end time and duration of each block into its context for output handlers to consume and report.
This should resolve issue #473
> Refactor test execution timing

- spec/modules/cli_spec.lua
This fixes a bad escape sequence used in spec/modules/cli_spec.lua for the last PR. Should be using '%' as the escape character instead of '\'. However, in order to be compatible with Lua 5.3, remove the parens from the match string for the failing test.
> Fix bad escape sequence

- completions/bash/busted.bash
This checks that the `_compopt_o_filenames` function exists before calling it. Otherwise, it just uses `compopt -o filenames` instead.
> Fix bash completion error

- busted/modules/test_file_loader.lua
This updates the test file loader to sort each group of test files it finds, preserving the order of any tests specified on the command-line.  As a result, the order of test files will be deterministic and will not
depend on the order that the files occur on the file-system.  This also makes shuffling test files reproducible across different systems when specifying the same random seed, assuming the version of Lua across these systems uses the same random number generator.
> Make test file order deterministic

- busted/block.lua
- busted/execute.lua
- busted/outputHandlers/gtest.lua
- busted/runner.lua
- spec/randomize_spec.lua
This adds support for an optional random seed parameter to be specified to the `randomize()` function.
```lua
describe('Randomizing test order with fixed seed', function()
randomize(123456) -- or randomize(true, 123456)
it('some test', function()
...
end)
it('another test', function()
...
end)
it('yet another test', function()
...
end)
end)
```
Or if you wanted your seed to be based on some random or pseudo-random input source
```lua
describe('Randomizing test order with using different random seeds', function()
describe('Random test group', function())
randomize(get_random_seed_from_device())
...
end)
describe('Another random test group', function())
randomize(get_random_seed_from_device())
...
end)
describe('Yet another random test group', function()) …
```
> Support optional seed parameter to randomize()

- busted/execute.lua
This fixes the random seed value that is displayed by some output handlers.  When a test suite is repeated multiple times with shuffle enabled and no random seed specified, then a new random seed is generated and used for each complete run of the test suite.  However, the random seed being sent to suite start at the beginning of each suite is incorrect when multiple runs are requested. In such cases, the seed passed to suite start is actually the seed for the previous run and not the current run that is being started. This change passes to suite start the random seed being used for the current run.
> Fix parameters sent to suite start

- busted/outputHandlers/TAP.lua
This fixes a bug in the TAP output handler causing busted to exit with an error when the `--suppress-pending` command-line option is used.
Fixes issue #518
> Fix TAP output handler for --suppress-pending option

- busted-2.0.rc12-1.rockspec
- busted-scm-0.rockspec
- busted/compatibility.lua
- busted/modules/cli.lua
- busted/modules/standalone_loader.lua
- busted/options.lua
- busted/runner.lua
- spec/cl_spec.lua
- spec/modules/cli_spec.lua
This adds support for running standalone tests via stdin to the Lua interpreter.
For example:
```
lua < standalone_spec.lua
```
or
```
cat standalone_spec.lua | lua
```
> Support running standalone tests from stdin

- busted/outputHandlers/junit.lua
The testcase time for junit output wasn't being output correctly.  This change will update the xml tag appropriately and include time in the output.
> Fix junit testcase time

- busted/outputHandlers/gtest.lua
- busted/outputHandlers/plainTerminal.lua
- busted/outputHandlers/utfTerminal.lua
This fixes a bug when trying to display an unsigned value using '%d', which will print a negative value when the value is too large.
> Use '%u' to format unsigned numbers

- README.md
It appears that "busted" is normally spelled with a lowercase 'b'. It was capitalized in the header.
> Make busted capitalization more consistent

- busted/outputHandlers/TAP.lua
8a4d223c5ae4ace8d88d4ee3ca79020f6e67ae21 changed the TAP handler to
write results after each test, but the output is still buffered.
If a test hangs, the buffered results of many previous tests will never
be printed, and it's not clear which test caused the hang. Flushing the
output avoids this.
cc @o-lim
> TAP handler: flush output immediately

- index.html
Requiring `mymodule` at the top level executes the code from the module at
that instance, so when later we define `_G._TEST = true` within the `setup`
function, `mymodule` has already been required and the global `_TEST` is
not set.
Solution is to declare the `mymodule` at the top, and then require it within
the `setup` function once the global `_TEST` has been set.
> Update private functions and CLI usage docs

- index.html
This heading has the same ID as the heading above it about `describe` blocks in general. A unique heading makes it easier to link to this section.
> Use a unique ID on heading about insulate/expose

- index.html
basicly the same as https://github.com/Olivine-Labs/luassert/pull/163, but because the busted docs is more elaborate and probably more looked at it makes sense to document it in both places.
> add explanation in README on how to do a `was_called_with` when mutating a table (or `self`).

- busted-scm-1.rockspec
- rockspecs/busted-2.0.0-1.rockspec
fixes #602 
After merge, the new rockspecs and rock (rock only for `2.0.0-1`, not for `scm-1`) should be uploaded to LuaRocks
> fix(rockspecs) proper usage of rockspec revision numbers

- .travis.yml
Since the published rockspecs are in their own dir, the SCM one is the only one in the main folder and hence a `luarocks make` is enough to build the currently checked out branch.
> fix(ci) do not specify a rockspec, just build the only one there

- busted/modules/files/terra.lua
A quick and simple fix to allow testing code from the latest version of terra rather than a four year old alpha build. Currently working.
Further revisions to come after changing terra to provide a requirable module to scripts running inside it that matches the library requireable from outside terra so that `require "terra"` will work.
That would allow using busted regardless of running it from the terra executable or luajit.
> Update terra loader to use the global-injection of current Terra

- busted/runner.lua
Busted already caches the `ffi.cdef` function, but `ffi.typeof` is
another candidate having the same re-register problem
> fix(luajit) also cache the `ffi.typeof` function

- busted/outputHandlers/TAP.lua
- busted/outputHandlers/base.lua
- busted/outputHandlers/gtest.lua
- busted/outputHandlers/json.lua
- busted/outputHandlers/junit.lua
- busted/outputHandlers/plainTerminal.lua
- busted/outputHandlers/sound.lua
- busted/outputHandlers/utfTerminal.lua
> fix(outputter) cache all functions, use io.write not print

- busted/modules/helper_loader.lua
- busted/runner.lua
- spec/cl_spec.lua
if the helper fails the tests should not run since the environment
is most likely not properly set up. This is a hard requirement.
fixes #549
> fix(helper) exit when cli specified helper fails

- busted/fixtures.lua
- busted/init.lua
- spec/fixtures_spec.lua
By providing a relative path from the current test file it will
return an absolute path to the fixture.
Closes #644
> feat(fixtures) add function to locate relative fixtures

- busted/fixtures.lua
- busted/init.lua
- spec/.hidden/dont_execute_spec.lua
- spec/.hidden/some_file.lua
- spec/fixtures_spec.lua
Also moves the `fixture_path` function (see #646) from a global to the 'fixtures' module. This is non-breaking since that hasn't been released yet.
I really don't like the global `fixture_path` hence the move into a separate module
```lua
local fixtures = "busted.fixtures"
local absolute_path = fixtures.path("../file/some/where.txt")
local my_file = fixtures.read("../file/some/where.txt")
local my_mod = fixtures.load("../some/path/file.lua")
```
> feat(fixtures) add helpers to read/load fixtures

- busted/context.lua
- spec/insulate-expose_spec.lua
Seems to be an easy fix, though I'd love feedback on [the `if` in line 22](https://github.com/Olivine-Labs/busted/pull/667/files#diff-5334561e9923d607069a41208ac1b79280fa64d315d6335ae9561ea3809dde60R22) of context.lua: I _don't think_ that there's a reason to restore if `rawget(_G, k) ~= nil` (as then it'd be restored in the first loop), right? 
Fixes #666
> Issue 666: restore globals set to nil in insulate block

- busted/outputHandlers/gtest.lua
- busted/outputHandlers/utfTerminal.lua
- spec/cl_output_handler.lua
this updates the color outputting handlers to take override options.
The 2 (utfTerminal and gtest) were not in sync to start with. The gtest one does not colorize output in CI runs since the stream is not a tty. This makes sense on local systems, but could use an override in CI to force the use of color.
Both outputters can now be forced by specifying outputter options;
- `--Xoutput "--color"` will force use of color
- `--Xoutput "--plain"` will force use without color
> fix(output) enable color overrides for utf+gtest handlers

- busted/outputHandlers/gtest.lua
- busted/outputHandlers/utfTerminal.lua
previously luassert did its own detection. Now the override in
busted will set luassert coloring options
see https://github.com/Olivine-Labs/luassert/pull/185#issuecomment-1206088029
> fix(color) utf+gtest handlers now also set luassert color

- README.md
Change does what it says on the tin. I was about to file an issue to clarify if this was the proper link when I saw a previous issue about it had already been closed and seemed to indicate this was the right one.
Rather than ask about it again I thought I'd just make a PR so future people don't get confused.
> Update official documentation link in the README so it doesn't lead to a 404 page

- .github/workflows/busted.yml
- busted-scm-1.rockspec
- busted-scm-2.rockspec
Resolves this error:
```
Cloning into 'busted'...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
Cf. <https://github.com/Olivine-Labs/busted/issues/668#issuecomment-1073215957>.
> Change rockspec URL to git+https

- .github/workflows/busted.yml
- .github/workflows/deploy.yml
- .github/workflows/versioning.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- action.yml
- busted-scm-2.rockspec
~~This is a false start, see comments in #689. A containerized Docker image is probably not the way to handle this because it needs to *execute* not just inspect the code it is testing. Probably an action that installs stuff in the host container is better.~~
A simple containerized GH Action release, per documentation best used for projects with no additional dependencies but adaptable to other uses as well.
> Setup repo for use *as* GH Action

- .github/workflows/busted.yml
> chore(ci) change to utfTerminal

- .github/workflows/busted.yml
- .luacov
- README.md
- spec/.hidden/.luacov
Closes #694.
If legit. I have some doubts. The status of async support isn't perfectly clear. We still have a spec file testing various aspects of it. I assume that's why I added the copas installation in 790a9f3 some time after it was removed in e8d51ac.
> chore(deps): Drop references to obsolete external dependency

- busted-scm-1.rockspec
"lfs" isn't being required in the codebase.
> fix(rockspec): remove luafilesystem, not a dependency

- README.md
There is no such table as "spy_on" inside "spy".
> chore(readme): fix the introductory example

- try
This change makes the `try` script work in environments that don't already have `LUA_PATH` set up the way `busted` needs.  The `try` script should eventually be replaced by a `Makefile` that also verifies external dependencies, but this will help for now.
> fix(testing): set LUA_PATH in try script

- busted/outputHandlers/utfTerminal.lua
My solution is the same as calling utf8.char.
_I did not use utf8.char because it was added in 5.3, and it would break on Lua version below it._
> Fixed utf8 characters not displaying in some environments

- busted/core.lua
- busted/outputHandlers/json.lua
Fixes issue #729
Also worth noting that a better way to handle json encode errors would probably be to report this via the json object instead of just outputting the error directly, but at least this way there is some output indicating the problem (previously no output about error would occur)
> fix(json-output): convert error object to string before encoding

- busted/outputHandlers/TAP.lua
This pr will fix the following error that if no test files:
```
busted --output=TAP
not ok 1 - 
/home/linuxbrew/.linuxbrew/opt/lua/bin/lua5.4: ...w/.linuxbrew/share/lua/5.4/busted/outputHandlers/TAP.lua:44: attempt to concatenate a nil value (field 'currentline')
stack traceback:
...w/.linuxbrew/share/lua/5.4/busted/outputHandlers/TAP.lua:44: in upvalue 'showFailure'
...w/.linuxbrew/share/lua/5.4/busted/outputHandlers/TAP.lua:87: in field 'fn'
/home/linuxbrew/.linuxbrew/share/lua/5.4/mediator.lua:103: in function </home/linuxbrew/.linuxbrew/share/lua/5.4/mediator.lua:96>
(...tail calls...)
...uxbrew/share/lua/5.4/busted/modules/test_file_loader.lua:46: in upvalue 'getTestFiles'
...uxbrew/share/lua/5.4/busted/modules/test_file_loader.lua:57: in upvalue 'getAllTestFiles' …
```
> fix(TAP-output): error if no test files

- busted/outputHandlers/junit.lua
**Features**:
- Support outputting Junit XML reports in suite dimension. When the scale of test cases is large, combining with some CI systems (eg: [Jenkins CI JUnit Realtime Test Reporter](https://plugins.jenkins.io/junit-realtime-test-reporter/)) can enable real-time viewing of test reports.
**Optimizations**:
- The current implementation is not friendly to the display of CI systems, and the hierarchy is not clear enough.
- Demo Link: https://jenkins.shan333.cn/job/busted_junit_demo/2/testReport/busted_demo.spec/ 
- ![before](https://github.com/lunarmodules/busted/assets/39296814/9b2607e1-1357-4f30-bedf-e8a46b55cc5e)
- Reason: CI System use the last one . to distinguish between package name and class name.
After optimizations:
- Demo Link: …
> opt: junit support split out; optimize display format

- busted-scm-1.rockspec
I haven't looked into *why* this was pinned in the first place yet, but whatever the reason I think we need to fix it at the source, not this way. This is making it hard to even test the cliargs module, much less release it.
> Unpin cliargs dependency

- busted-scm-1.rockspec
- busted/modules/files/fennel.lua
Closes #738
Tests can be written in Fennel if `fennel` is among the loaders. Currently the traceback is wrong for failures and pending tests, but it is wrong for tests written in Moonscript as well, so this seems to be a general problem with busted.
It would have been cool if we could make `it`, `describe` and so on into macros to not have to manually wrap the test body inside a thunk every time.
```fennel
;; With macro
(it "Adds two numbers"
(assert.are.equal 5 (+ 2 3)))
;; Without macro
(it "Adds two numbers"
(fn []
(assert.are.equal 5 (+ 2 3))))
```
This macro can accomplish it when added to the beginning of a test:
```fennel
(macro it [description & body]
`(let [fenv# (or (and getfenv (getfenv)) _ENV)]
((. fenv# :it) ,description
(fn [] ,(unpack body)))))
```
However, the source map …
> Implement loader for Fennel

- busted/outputHandlers/junit.lua
The junit output handler extracts package name from trace.short_src, which size is limited to 60 in [the source of lua](https://github.com/lua/lua/blob/c1dc08e8e8e22af9902a6341b4a9a9a7811954cc/lua.h#L508).
When my test file located in a deep path, the junit report will be truncated.
In this PR, I use trace.source instead of trace.short_src.
> opt: truncated package name in junit report

- busted/modules/cli.lua
- busted/runner.lua
- spec/cl_spec.lua
Fixes #697
This change adds a check on the error returned from the `cliargs` library, and provides a "help" argument to the consumer code in `busted/runner.lua`.
It is based on the workaround used with the same library here: https://github.com/sile-typesetter/sile/pull/1737/files
except that the code in `busted/runner.lua` probably won't need to change if `cliargs` ever supports adding a `--help` flag in the "correct" way.
> Hack around cliargs to provide "help" flag
