lunarmodules/busted

busted/outputHandlers/junit.lua
This fixes the following errors in the junit output handler:
* Skip test count
* Failure stack trace message
* Missing error tags for describe/it errors
* Missing trace info causes busted to crash (issue #333)
* Missing pending (skip) tags
=> Fix junit output

busted/modules/files/moonscript.lua, busted/modules/files/terra.lua, busted/modules/output_handler_loader.lua, busted/runner.lua
* Simplify moonscript and terra file loaders
* Cleanup error handling in output handler loader
* Add support for loading moonscript output handlers
=> Cleanup output handler loader and file loaders

busted/core.lua, busted/init.lua, busted/modules/configuration_loader.lua, busted/modules/files/lua.lua, busted/modules/files/moonscript.lua, busted/modules/files/terra.lua, busted/modules/test_file_loader.lua, busted/outputHandlers/TAP.lua, busted/outputHandlers/base.lua, busted/outputHandlers/json.lua, busted/outputHandlers/junit.lua, busted/outputHandlers/sound.lua, busted/runner.lua
Some easy tiny fixes here and there. Other issues I found but didn't fix:
* [broken sound output handler](https://github.com/Olivine-Labs/busted/blob/1b6fd688c62d53e931d0e6d11f5034066634c083/busted/outputHandlers/sound.lua#L8-L21) - `system` is never set;
* [utils.normpath is broken on Windows on UNC](https://github.com/Olivine-Labs/busted/blob/1a46685129f3f0e4204f2c710aff1530c915220c/busted/utils.lua#L18) - `normpath` is not a variable;
* ["it" publishes something wrong](https://github.com/Olivine-Labs/busted/blob/f2f56623554f81d46c5a657f6c1111212c91d318/busted/init.lua#L137) - where did `parent` come from?
Hope this helps.
=> Clean up some unused and global variables

busted/compatibility.lua, busted/runner.lua
=> fix memoryleak in userdata on os.exit in Lua 5.1

busted/languages/es.lua
=> Adding Spanish language for error handling

busted-2.0.rc7-0.rockspec
Added missing es language file busted-2.0 rockspec.
=> Add Spanish language to rockspec

busted/outputHandlers/TAP.lua
This updates the TAP output handler to output the result of each test as it completes, instead of displaying all test results at the end of a suite. Also update TAP output to report skipped tests and errors occurring outside of tests.
```
$ busted -o TAP
ok 1 - Tests success1
ok 2 - Tests success2
not ok 3 - Tests failure1
not ok 4 - Tests failure2
not ok 5 - Tests error1
not ok 6 - Tests error2
ok 7 - # SKIP Tests pending1
ok 8 - # SKIP spec/test_spec.lua:32: pending2
not ok 9 - Tests teardown
1..9
```
```
$ busted -v -o TAP
ok 1 - Tests success1
ok 2 - Tests success2
not ok 3 - Tests failure1
#
not ok 4 - Tests failure2
#
not ok 5 - Tests error1
#
not ok 6 - Tests error2
#
ok 7 - # SKIP Tests pending1
ok 8 - # SKIP spec/test_spec.lua:32: pending2
not ok 9 - Tests teardown
#
1..9
``` …
=> Update TAP output handler

busted/execute.lua, busted/modules/test_file_loader.lua, busted/runner.lua, spec/cl_spec.lua
This fixes test file loading when running a test in standalone mode.
=> Fix test file loading

.travis.yml, .travis_setup.sh
Update travis builds to use latest versions of Lua and LuaJIT
=> Update version of Lua/LuaJIT used by travis builds

busted-scm-0.rockspec
=> Update rockspec to use https url for cloning

index.html
This updates the `busted` website with the following:
* Fixes tag examples
* Fixes broken github URLs
* Update usage
* Update busted task description
* Update Private section
* Update Output Handler example
=> Update website descriptions

busted/core.lua
=> Fix incorrect busted.version

.travis.yml, .travis_setup.sh
This adds a backup server from which to download luarocks, and updates the luarocks version to 2.2.2
=> Add luarocks backup server for travis build

.travis.yml, .travis_setup.sh, busted/core.lua
This simplifies the error status detection and make it more robust in case a user defined error object has a similar metatable.
=> Refactor error type detection

.travis_setup.sh
Update to the latest version of LuaJIT
=> Update travis build to use LuaJIT v2.0.4

index.html
Add section on running in standalone mode.
=> Update website with description of standalone mode

index.html
Update gh-pages with fixed busted task example.
Resolves issue #436.
=> Fix busted task example in documentation

busted/outputHandlers/gtest.lua
This fixes the file test count when using the gtest output handler
=> Fix file test count for gtest output handler

busted-2.0.rc10-0.rockspec, busted-scm-0.rockspec
Update `lua_cliargs` version dependency to be >= 2.5, < 3.0
=> Update lua_cliargs dependency

busted-scm-0.rockspec, busted/utils.lua
This just removes an unused variable from utils.
=> Remove unused variable from utils

busted/block.lua, busted/execute.lua, busted/modules/filter_loader.lua, busted/runner.lua
This updates the `--list` command-line option to honor `--sort`, `--shuffle`, and `--suppress-pending` flags.
=> Option --list honors --sort, --shuffle, --suppress-pending

busted/modules/configuration_loader.lua, busted/runner.lua
=> fix LuaJIT segfault due to ffi reloading

busted/outputHandlers/TAP.lua, busted/outputHandlers/gtest.lua, busted/outputHandlers/junit.lua, busted/outputHandlers/plainTerminal.lua, busted/outputHandlers/sound.lua, busted/outputHandlers/utfTerminal.lua
=> Cache io to be robust about mocking io in tests

.luacheckrc, .travis.yml, busted/languages/zh.lua, busted/modules/helper_loader.lua, busted/outputHandlers/base.lua, busted/outputHandlers/gtest.lua, busted/outputHandlers/junit.lua, spec/cl_errors.lua, spec/cl_spec.lua, spec/core_spec.lua, spec/expose_file1.lua, spec/expose_file2.lua, spec/insulate_file1.lua, spec/insulate_file2.lua, spec/modules/cli_spec.lua, spec/modules/file_loader_spec.lua, spec/modules/luacov_spec.lua, spec/modules/output_handler_loader_spec.lua, spec/strict.lua, try
The first commit adds the linter setup and fixes the existing issues found
The second one adds it to the CI setup
closes #620
=> Add linter

.travis.yml, .travis/setup_lua.sh
the 2.0 version is not installed from source, only the 2.1 was.
despite that the "luajit" option also installs 2.1 (but from a
tar ball)
=> fix(ci) fix LuaJIT2.0.x setup

busted-scm-2.rockspec, busted/luajit.lua, busted/runner.lua, spec/luajit_spec.lua
Abstracts the patching into its own module as well
fixes #630
=> fix(luajit) add 'metatype' as a patched method

index.html
=> fix(docs) typo in example

README.md
=> fix(readme): Correct link to test runner badge

busted-scm-2.rockspec
and sort for easier comparison
=> fix(rockspec) add missing languages

index.html
[#685 ](https://github.com/Olivine-Labs/busted/issues/682)
=> Explanation for matcher behavior
